### ISSUE TITLE
Executing jobs using garden-linux create getpwnam error

### ISSUE THREAD

**Issue by kicombs** [cloudfoundry-incubator/garden-linux#63]
As per a conversation with the concourse team, we had the following issue occur across multiple ci builds (when they were working just fine minutes before)
```
error streaming in: exit status 1. Output: getpwnam: No such file or directory
```

stemcell                    3197
garden-linux             0.332.0
linux kernel version  3.13.0-48-generic
concourse                0.73.0
go                             go1.5 linux/amd64

Our docker image had the following fields present (checked as per recommendation):
```
/etc/passwd
/etc/group
/etc/shadow
/etc/nsswitch.conf
```
nothing looked amiss in any of these files.

After debugging with the team, we kicked off a formerly failing build and the above error went away. We don't know what the issue was, and don't know how to reproduce it. We were also unable to get information from executing an strace.

Strange thing about this issue when it was a problem was that some tasks running in the concourse container would execute, but others would not.

**Comment by goonzoid** [comment]
Thanks @kicombs. Please do let us know if you see this again.

Is there a public image we could try to reproduce this with?

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#116969629](https://www.pivotaltracker.com/story/show/116969629) Executing jobs using garden-linux create getpwnam error


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by aquavitae** [comment]
I'm getting the same issue using the vagrant lite box with the following (slightly modified) hello world example.  We have a proxy setup which means using insecure SSL, but that's shouldn't affect this.

```yml
jobs:
  - name: hello-world
    plan:
      - task: say-hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: registry-1.docker.io/library/ubuntu
              insecure_registries: 
                - registry-1.docker.io
          run:
            path: echo
            args: ["Hello, world!"]
```
